'use client';
import { useLocale } from '@/lib/i18n/use-locale';
import { SoklaroMark } from '../components/soklaro-mark';



export default function PrivacyPage() {
  const { t } = useLocale();
  return <main className="privacy-page"><header><a className="brand-mark" href="/"><span><SoklaroMark /></span>soklaro</a><nav><a href="/impressum">{t("Impressum")}</a><a href="/app">{t("Wetter öffnen")}</a></nav></header><p className="eyebrow">{t("Stand 5. September 2026")}</p><h1>{t("Netzwerk &")}<br />{t("Datenschutz")}</h1><p>{t("soklaro ist 100 % werbe- und trackerfrei. Das bedeutet nicht, dass bei Online-Wetterabrufen gar keine Daten übertragen werden. Diese Seite führt die erlaubten Verbindungen und ihren Zweck vollständig auf.")}</p>
    <h2>{t("Erlaubte externe Hosts")}</h2><ul className="host-list"><li><code>api.open-meteo.com</code><span>{t("Wetterprognosen. Übertragen werden IP-Adresse sowie gewählte oder gerundete Koordinaten.")}</span></li><li><code>geocoding-api.open-meteo.com</code><span>{t("Ortssuche. Übertragen werden IP-Adresse und der eingegebene Suchbegriff.")}</span></li><li><code>nominatim.openstreetmap.org</code><span>{t("Einmalige Benennung eines bewusst freigegebenen GPS-Standorts. Übertragen werden IP-Adresse sowie die zuvor gewählten oder gerundeten Koordinaten.")}</span></li></ul><p>{t("Bei konfigurierter Kunden- oder Self-Hosting-Instanz werden die Open‑Meteo-Hosts durch die ausdrücklich konfigurierte Basis-URL ersetzt. Es gibt keine externen Schrift-, Bild-, Analytics-, Werbe- oder JavaScript-CDN-Verbindungen.")}</p>
    <h2>Open‑Meteo</h2><p>{t("Die öffentliche API erhält technisch deine IP-Adresse und die abgefragten Koordinaten. Open‑Meteo erklärt, Protokolldaten für bis zu 90 Tage aufzubewahren. Der Standard-Build nutzt die öffentliche API ausschließlich nichtkommerziell; kommerzielle Betreiber müssen einen Kunden-Proxy oder eine selbst gehostete Instanz konfigurieren. Maßgeblich sind die")} <a href="https://open-meteo.com/en/terms" rel="noreferrer">{t("Bedingungen von Open‑Meteo")}</a>{t(". soklaro sendet diese Daten nicht an Werbepartner.")}</p>
    <h2>{t("Standort")}</h2><p>{t("Der Gerätestandort wird niemals beim ersten Laden angefragt, sondern ausschließlich nach Betätigung von „Meinen Standort verwenden“. Exakte Koordinaten werden standardmäßig nicht dauerhaft gespeichert. Optional werden Koordinaten vor der Anfrage auf ungefähr 1 km oder 5 km gerundet. Besonders in Gebirgen und Küstenregionen kann das die Vorhersage und den angezeigten Ortsnamen beeinflussen. Zur Ortsbenennung fragt die App nach derselben Nutzeraktion einmalig den öffentlichen Nominatim-Dienst von OpenStreetMap ab; maßgeblich sind dessen")} <a href="https://operations.osmfoundation.org/policies/nominatim/" rel="noreferrer">{t("Nutzungsregeln")}</a>{t(". Der ermittelte Ort wird lokal als letzter Ort gespeichert und nicht bei jedem Start neu abgefragt.")}</p>
    <h2>{t("Lokale Daten")}</h2><p>{t("Favoriten, benutzerdefinierte Namen, Einheiten, Sprache, Einstellungen und die letzte erfolgreiche Prognose werden ausschließlich auf deinem Gerät gespeichert. „Alle lokalen Daten löschen“ im App-Menü entfernt diese Werte sofort. soklaro setzt keine Cookies.")}</p>
    <h2>{t("Selbst hosten")}</h2><p>{t("Setze")} <code>VITE_OPEN_METEO_URL</code> {t("und")} <code>VITE_OPEN_METEO_GEOCODING_URL</code> {t("auf die HTTPS-Basis-URLs deiner Open‑Meteo-Instanz und baue die App neu. Geheime API-Schlüssel dürfen nicht in Client-Variablen oder das Repository geschrieben werden. Kundenendpunkte mit Geheimnissen benötigen einen eigenen serverseitigen Proxy.")}</p>
    <h2>{t("Nicht enthalten")}</h2><p>{t("Keine Werbung, Analytics, Telemetrie, Tracking-Pixel, Session-Replays, Fingerprinting-, Crash-Reporting-, Social-Media- oder Marketing-SDKs. Keine Nutzerkonten, Cloud-Synchronisierung, externen Fonts, Remote-Wetterbilder oder ungefragten Push-Benachrichtigungen.")}</p>
  </main>;
}
