import { SoklaroMark } from '../components/soklaro-mark';

export const metadata = { title: 'Netzwerk & Datenschutz', description: 'Alle Netzwerkverbindungen und lokalen Daten von soklaro.' };

export default function PrivacyPage() {
  return <main className="privacy-page"><header><a className="brand-mark" href="/"><span><SoklaroMark /></span>soklaro</a><nav><a href="/impressum">Impressum</a><a href="/app">Wetter öffnen</a></nav></header><p className="eyebrow">Stand 2. September 2026</p><h1>Netzwerk &<br />Datenschutz</h1><p>soklaro ist 100 % werbe- und trackerfrei. Das bedeutet nicht, dass bei Online-Wetterabrufen gar keine Daten übertragen werden. Diese Seite führt die erlaubten Verbindungen und ihren Zweck vollständig auf.</p>
    <h2>Erlaubte externe Hosts</h2><ul className="host-list"><li><code>api.open-meteo.com</code><span>Wetterprognosen. Übertragen werden IP-Adresse sowie gewählte oder gerundete Koordinaten.</span></li><li><code>geocoding-api.open-meteo.com</code><span>Ortssuche. Übertragen werden IP-Adresse und der eingegebene Suchbegriff.</span></li></ul><p>Bei konfigurierter Kunden- oder Self-Hosting-Instanz werden diese Hosts durch die ausdrücklich konfigurierte Basis-URL ersetzt. Es gibt keine externen Schrift-, Bild-, Analytics-, Werbe- oder JavaScript-CDN-Verbindungen.</p>
    <h2>Open‑Meteo</h2><p>Die öffentliche API erhält technisch deine IP-Adresse und die abgefragten Koordinaten. Open‑Meteo erklärt, Protokolldaten für bis zu 90 Tage aufzubewahren. Der Standard-Build nutzt die öffentliche API ausschließlich nichtkommerziell; kommerzielle Betreiber müssen einen Kunden-Proxy oder eine selbst gehostete Instanz konfigurieren. Maßgeblich sind die <a href="https://open-meteo.com/en/terms" rel="noreferrer">Bedingungen von Open‑Meteo</a>. soklaro sendet diese Daten nicht an Werbepartner.</p>
    <h2>Standort</h2><p>Der Gerätestandort wird niemals beim ersten Laden angefragt, sondern ausschließlich nach Betätigung von „Meinen Standort verwenden“. Exakte Koordinaten werden standardmäßig nicht dauerhaft gespeichert. Optional werden Koordinaten vor der Anfrage auf ungefähr 1 km oder 5 km gerundet. Besonders in Gebirgen und Küstenregionen kann das die Vorhersage beeinflussen. Für die Benennung des aktuellen Standorts wird kein zweiter Reverse-Geocoding-Dienst aufgerufen.</p>
    <h2>Lokale Daten</h2><p>Favoriten, benutzerdefinierte Namen, Einheiten, Sprache, Einstellungen und die letzte erfolgreiche Prognose werden ausschließlich auf deinem Gerät gespeichert. „Alle lokalen Daten löschen“ im App-Menü entfernt diese Werte sofort. soklaro setzt keine Cookies.</p>
    <h2>Selbst hosten</h2><p>Setze <code>VITE_OPEN_METEO_URL</code> und <code>VITE_OPEN_METEO_GEOCODING_URL</code> auf die HTTPS-Basis-URLs deiner Open‑Meteo-Instanz und baue die App neu. Geheime API-Schlüssel dürfen nicht in Client-Variablen oder das Repository geschrieben werden. Kundenendpunkte mit Geheimnissen benötigen einen eigenen serverseitigen Proxy.</p>
    <h2>Nicht enthalten</h2><p>Keine Werbung, Analytics, Telemetrie, Tracking-Pixel, Session-Replays, Fingerprinting-, Crash-Reporting-, Social-Media- oder Marketing-SDKs. Keine Nutzerkonten, Cloud-Synchronisierung, externen Fonts, Remote-Wetterbilder oder ungefragten Push-Benachrichtigungen.</p>
  </main>;
}
