'use client';
import { useLocale } from '@/lib/i18n/use-locale';
import { ArrowUpRight } from 'lucide-react';
import { SoklaroMark } from './components/soklaro-mark';
import { projectLinks } from '@/lib/project';

const features = [
  ['01', 'Wetter, das atmen darf', 'Aktuell, 48 Stunden und 14 Tage – mit klarer Hierarchie statt Kartenchaos.'],
  ['02', 'Standort unter deiner Kontrolle', 'Keine automatische Abfrage. Du entscheidest, ob Koordinaten exakt, auf etwa 1 km oder auf etwa 5 km gerundet werden.'],
  ['03', 'Offline ehrlich', 'Die letzte erfolgreiche Prognose bleibt verfügbar – sichtbar als gespeichert und mit ihrem Alter, niemals als vermeintlich aktuell.'],
  ['04', 'Lokale Wetterhinweise', 'Regenbeginn, UV, Böen und Temperaturspitzen werden deterministisch auf deinem Gerät abgeleitet.'],
  ['05', 'Europa im Fokus', 'Open‑Meteo wählt geeignete Modelle wie DWD ICON, ECMWF oder Météo‑France automatisch aus.'],
  ['06', 'Offener Quellcode', 'MPL‑2.0, nachvollziehbare Datenflüsse und reproduzierbare Builds für Web, iOS und Android.'],
];

export default function LandingPage() {
  const { t } = useLocale();
  return <main className="landing">
    <header className="landing-nav"><a className="brand-mark" href="/" aria-label={t("soklaro Startseite")}><span><SoklaroMark /></span>soklaro</a><nav aria-label={t("Hauptnavigation")}><a href="#privacy">{t("Datenschutz")}</a><a href="#features">{t("Funktionen")}</a><a href="#install">{t("Installieren")}</a><a className="nav-cta" href="/app">{t("Wetter öffnen")}</a></nav></header>
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">{t("Offen · ruhig · privat")}</p><h1>{t("Das Wetter für deinen Ort.")} <em>{t("Nicht für Werbenetzwerke.")}</em></h1><p>{t("soklaro verbindet atmosphärisches Wetterdesign mit einer überprüfbaren Privacy-Architektur: werbefrei, trackerfrei, ohne Konto und ohne Standortverlauf.")}</p><div className="hero-actions"><a className="primary" href="/app">{t("Wetter öffnen")} <ArrowUpRight /></a><a className="secondary" href="#privacy">{t("Wie Standortschutz funktioniert")}</a></div></div><div className="phone-preview" aria-label={t("Produktvorschau der soklaro Wetter-App")}><p className="eyebrow">{t("Dein Wetter")}</p><h2>Berlin</h2><p>{t("14:20 · Teilweise bewölkt")}</p><div className="mini-temp">22°</div><p>{t("Gefühlt 21° · H 23° / T 13°")}</p><div className="mini-insight">{t("Regen wahrscheinlich ab 16:00.")}</div></div></section>
    <section className="trust-strip" aria-label={t("Produktversprechen")}><div><strong>0</strong><small>{t("Werbung & Tracker")}</small></div><div><strong>0</strong><small>{t("Nutzerkonten")}</small></div><div><strong>{t("Lokal")}</strong><small>{t("Favoriten & Einstellungen")}</small></div><div><strong>{t("Offen")}</strong><small>{t("MPL‑2.0 Quellcode")}</small></div></section>
    <section className="story" id="privacy"><div><p className="eyebrow">{t("Privacy, sachlich erklärt")}</p><h2>{t("Weniger Daten. Mehr Vorhersage.")}</h2></div><div className="story-copy"><p>{t("Viele kostenlose Wetter-Apps finanzieren sich mit Werbe- und Tracking-SDKs. soklaro verzichtet bewusst vollständig darauf. Für einen Online-Wetterabruf werden trotzdem technische Daten übertragen – insbesondere deine IP-Adresse sowie die gewählten oder gerundeten Koordinaten an Open‑Meteo.")}</p><p>{t("Beim Start fragen wir niemals automatisch nach deinem Standort. Suche einen Ort oder erteile den Zugriff bewusst; auf Wunsch wird die Position vor der Übertragung gerundet.")}</p><div className="network-flow"><div><strong>{t("Dein Gerät")}</strong><span>{t("speichert Favoriten, Einstellungen und die letzte Prognose lokal")}</span></div><div><strong>Open‑Meteo</strong><span>{t("erhält Suchbegriff oder Koordinaten und liefert Wetterdaten")}</span></div><div><strong>OpenStreetMap</strong><span>{t("benennt den Standort einmalig nach deiner GPS-Freigabe")}</span></div><div><strong>{t("Keine Werbepartner")}</strong><span>{t("kein Analytics, keine Social SDKs und keine Remote-Wetterbilder")}</span></div></div><p><a href="/privacy">{t("Alle Netzwerkverbindungen ansehen →")}</a></p></div></section>
    <section className="features" id="features"><p className="eyebrow">{t("Im ersten Blick das Wesentliche")}</p><h2>{t("Schön genug für jeden Tag.")}<br />{t("Streng genug für dein Vertrauen.")}</h2><div className="feature-grid">{features.map(([number,title,copy]) => <article key={number}><span>{number}</span><h3>{t(title)}</h3><p>{t(copy)}</p></article>)}</div></section>
    <section className="install" id="install"><div><p className="eyebrow">Website · PWA · iOS · Android</p><h2>{t("Ein Zuhause auf jedem Bildschirm.")}</h2><p>{t("Die Web-Codebasis bleibt führend. Die PWA funktioniert nach dem ersten erfolgreichen Besuch offline; Capacitor verpackt dieselbe App für die nativen Stores.")}</p></div><ol><li><div><strong>{t("Im Browser öffnen")}</strong><small>{t("Ohne Konto direkt auf /app starten.")}</small></div></li><li><div><strong>{t("Zum Startbildschirm hinzufügen")}</strong><small>{t("Im Browsermenü „App installieren“ wählen.")}</small></div></li><li><div><strong>{t("Nativ bauen")}</strong><small>{t("Die dokumentierten Capacitor-Builds nutzen. Store-Konten von Apple und Google können Gebühren verursachen.")}</small></div></li></ol></section>
    <section className="faq"><p className="eyebrow">{t("Häufige Fragen")}</p><h2>{t("Transparenz statt Kleingedrucktem.")}</h2><details><summary>{t("Ist soklaro wirklich ohne Tracking?")}</summary><p>{t("Ja. Die ausgelieferte App enthält keine Analytics-, Werbe-, Telemetrie-, Session-Replay- oder Crash-Reporting-SDKs. Wetterabrufe sind dennoch Netzwerkzugriffe; sie werden vollständig dokumentiert.")}</p></details><details><summary>{t("Werden exakte Koordinaten gespeichert?")}</summary><p>{t("Standardmäßig nicht dauerhaft. Du kannst Koordinaten außerdem vor dem Wetterabruf auf ungefähr 1 km oder 5 km runden. Gröbere Rundung kann besonders an Küsten und in Gebirgen die Prognose beeinflussen.")}</p></details><details><summary>{t("Welche Datenquelle wird genutzt?")}</summary><p>{t("Standardmäßig Open‑Meteo mit automatischer Modellauswahl. Der Endpunkt ist konfigurierbar, sodass auch eine Kunden- oder selbst gehostete Instanz verwendet werden kann.")}</p></details><details><summary>{t("Kann ich soklaro mitgestalten?")}</summary><p>{t("Ja. Code, Übersetzungen, Design und Dokumentation sind offen für Beiträge.")}</p></details></section>
    <footer className="landing-footer"><div><h2>soklaro</h2><p>{t("Freies Wetter ohne Werbung, Konto oder Standortverlauf.")}</p></div><nav aria-label={t("Projekt")}><strong>{t("Projekt")}</strong><a href="/app">{t("Wetter öffnen")}</a><a href="/privacy">{t("Datenschutz")}</a>{projectLinks.repository && <a href={projectLinks.repository} rel="noreferrer">{t("Quellcode")}</a>}</nav><nav aria-label={t("Rechtliches")}><strong>{t("Rechtliches")}</strong><a href="/privacy">{t("Netzwerk & Datenschutz")}</a><a href="/impressum">{t("Impressum")}</a><a href="/legal/security.txt">{t("Sicherheit")}</a><a href="/legal/third-party-licenses.txt">{t("Lizenzen")}</a></nav></footer>
  </main>;
}
