'use client';
import { useLocale } from '@/lib/i18n/use-locale';
import { ArrowUpRight } from 'lucide-react';
import { SoklaroMark } from './components/soklaro-mark';
import { projectLinks } from '@/lib/project';

export default function LandingPage() {
  const { t } = useLocale();
  return <main className="landing">
    <header className="landing-nav"><a className="brand-mark" href="/" aria-label={t("soklaro Startseite")}><span><SoklaroMark /></span>soklaro</a><nav aria-label={t("Hauptnavigation")}><a href="#privacy">{t("Datenschutz")}</a><a className="nav-cta" href="/app">{t("Wetter öffnen")}</a></nav></header>
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">{t("Offen · ruhig · privat")}</p><h1>{t("Das Wetter für deinen Ort.")} <em>{t("Nicht für Werbenetzwerke.")}</em></h1><p>{t("soklaro verbindet atmosphärisches Wetterdesign mit einer überprüfbaren Privacy-Architektur: werbefrei, trackerfrei, ohne Konto und ohne Standortverlauf.")}</p><div className="hero-actions"><a className="primary" href="/app">{t("Wetter öffnen")} <ArrowUpRight /></a><a className="secondary" href="#privacy">{t("Wie Standortschutz funktioniert")}</a></div></div><div className="phone-preview" aria-label={t("Produktvorschau der soklaro Wetter-App")}><p className="eyebrow">{t("Dein Wetter")}</p><h2>Hamburg</h2><p>{t("14:20 · Teilweise bewölkt")}</p><div className="mini-temp">22°</div><p>{t("Gefühlt 21° · H 23° / T 13°")}</p><div className="mini-insight">{t("Regen wahrscheinlich ab 16:00.")}</div></div></section>
    <section className="trust-strip" aria-label={t("Produktversprechen")}><div><strong>0</strong><small>{t("Werbung & Tracker")}</small></div><div><strong>0</strong><small>{t("Nutzerkonten")}</small></div><div><strong>{t("Lokal")}</strong><small>{t("Favoriten & Einstellungen")}</small></div><div><strong>{t("Offen")}</strong><small>{t("MPL‑2.0 Quellcode")}</small></div></section>
    <section className="story" id="privacy"><div><p className="eyebrow">{t("Privacy, sachlich erklärt")}</p><h2>{t("Weniger Daten. Mehr Vorhersage.")}</h2></div><div className="story-copy"><p>{t("Viele kostenlose Wetter-Apps finanzieren sich mit Werbe- und Tracking-SDKs. soklaro verzichtet bewusst vollständig darauf. Für einen Online-Wetterabruf werden trotzdem technische Daten übertragen – insbesondere deine IP-Adresse sowie die gewählten oder gerundeten Koordinaten an Open‑Meteo.")}</p><p>{t("Beim Start fragen wir niemals automatisch nach deinem Standort. Suche einen Ort oder erteile den Zugriff bewusst; auf Wunsch wird die Position vor der Übertragung gerundet.")}</p><div className="network-flow"><div><strong>{t("Dein Gerät")}</strong><span>{t("speichert Favoriten, Einstellungen und die letzte Prognose lokal")}</span></div><div><strong>Open‑Meteo</strong><span>{t("erhält Suchbegriff oder Koordinaten und liefert Wetterdaten")}</span></div><div><strong>OpenStreetMap</strong><span>{t("benennt den Standort einmalig nach deiner GPS-Freigabe")}</span></div><div><strong>{t("Keine Werbepartner")}</strong><span>{t("kein Analytics, keine Social SDKs und keine Remote-Wetterbilder")}</span></div></div><p><a href="/privacy">{t("Alle Netzwerkverbindungen ansehen →")}</a></p></div></section>
    <section className="faq"><p className="eyebrow">{t("Häufige Fragen")}</p><h2>{t("Transparenz statt Kleingedrucktem.")}</h2><details><summary>{t("Ist soklaro wirklich ohne Tracking?")}</summary><p>{t("Ja. Die ausgelieferte App enthält keine Analytics-, Werbe-, Telemetrie-, Session-Replay- oder Crash-Reporting-SDKs. Wetterabrufe sind dennoch Netzwerkzugriffe; sie werden vollständig dokumentiert.")}</p></details><details><summary>{t("Werden exakte Koordinaten gespeichert?")}</summary><p>{t("Standardmäßig nicht dauerhaft. Du kannst Koordinaten außerdem vor dem Wetterabruf auf ungefähr 1 km oder 5 km runden. Gröbere Rundung kann besonders an Küsten und in Gebirgen die Prognose beeinflussen.")}</p></details><details><summary>{t("Welche Datenquelle wird genutzt?")}</summary><p>{t("Standardmäßig Open‑Meteo mit automatischer Modellauswahl. Der Endpunkt ist konfigurierbar, sodass auch eine Kunden- oder selbst gehostete Instanz verwendet werden kann.")}</p></details><details><summary>{t("Kann ich soklaro mitgestalten?")}</summary><p>{t("Ja. Code, Übersetzungen, Design und Dokumentation sind offen für Beiträge.")}</p></details></section>
    <footer className="landing-footer"><div><h2>soklaro</h2><p>{t("Freies Wetter ohne Werbung, Konto oder Standortverlauf.")}</p></div><nav aria-label={t("Projekt")}><strong>{t("Projekt")}</strong><a href="/app">{t("Wetter-App öffnen")}</a><a href="/privacy">{t("Datenschutz")}</a>{projectLinks.repository && <a href={projectLinks.repository} rel="noreferrer">{t("Quellcode")}</a>}</nav><nav aria-label={t("Rechtliches")}><strong>{t("Rechtliches")}</strong><a href="/privacy">{t("Netzwerk & Datenschutz")}</a><a href="/impressum">{t("Impressum")}</a><a href="/legal/third-party-licenses.txt">{t("Lizenzen")}</a></nav></footer>
  </main>;
}
